backend/base/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from base import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
    path('schemas/', include('schemas.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

handler400 = 'schemas.views.handler400'
handler403 = 'schemas.views.handler403'
handler404 = 'schemas.views.handler404'
handler500 = 'schemas.views.handler500'

backend/schemas/urls.py
from django.urls import path

from schemas.views import (
    ListSchemaView, CreateSchemaView,
    UpdateSchemaView, DeleteSchemaView,
    RetrieveSchemaView, generate_file_view,
    download_file_view
)


app_name = 'schemas'

urlpatterns = [
    path('list/', ListSchemaView.as_view(), name='list'),
    path('create/', CreateSchemaView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateSchemaView.as_view(), name='update'),
    path('delete/<int:pk>/', DeleteSchemaView.as_view(), name='delete'),
    path('retrieve/<int:pk>/', RetrieveSchemaView.as_view(), name='retrieve'),
    path('generate/<int:pk>/', generate_file_view, name='generate'),
    path('download/<int:pk>/', download_file_view, name='download'),
]

backend/users/urls.py
from django.urls import path

from users.views import LoginUserView, logout_user


app_name = 'users'

urlpatterns = [
    path('login/', LoginUserView.as_view(), name='login'),
    path('logout/', logout_user, name='logout'),
]

backend/schemas/models.py
from django.contrib.auth import get_user_model
from django.db import models


COLUMN_SEPARATOR_CHOICES = (
    (",", "Comma (,)"),
    (";", "Semicolon (;)"),
)
STRING_CHARACTER_CHOICES = (
    ('"', 'Double-quote (")'),
    ("'", "Single-quote (')"),
)
COLUMN_TYPE_CHOICES = (
    ("1", "Full name"),
    ("2", "Email"),
    ("3", "Phone number"),
    ("4", "Address"),
    ("5", "Date"),
)
COLUMN_TYPE_DICT = dict(COLUMN_TYPE_CHOICES)


class Schema(models.Model):
    name = models.CharField(max_length=50)
    column_separator = models.CharField(max_length=1, default=",",
                                        choices=COLUMN_SEPARATOR_CHOICES)
    string_character = models.CharField(max_length=1, default='"',
                                        choices=STRING_CHARACTER_CHOICES)
    modified = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='schemas')

    def __str__(self):
        return self.name


class Column(models.Model):
    name = models.CharField(max_length=50)
    type = models.CharField(max_length=1, choices=COLUMN_TYPE_CHOICES)
    order = models.IntegerField()
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE,
                               related_name='columns')

    def __str__(self):
        return self.name

    def get_type_name(self):
        return COLUMN_TYPE_DICT[self.type]


class DataSet(models.Model):
    path = models.FilePathField()
    created = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10)
    schema = models.ForeignKey(Schema, on_delete=models.CASCADE,
                               related_name='datasets')

    @classmethod
    def get_next_sequence_number(cls, schema_id):
        return cls.objects.filter(schema_id=schema_id).count()

backend/schemas/forms.py
from django import forms

from schemas.models import Schema, Column


class SchemaForm(forms.ModelForm):
    class Meta:
        model = Schema
        fields = ('name', 'column_separator', 'string_character')


ColumnCreateFormSet = forms.modelformset_factory(
    Column,
    fields=('name', 'type', 'order'),
    extra=1
)

ColumnUpdateFormSet = forms.modelformset_factory(
    Column,
    fields=('name', 'type', 'order'),
    extra=0
)

backend/schemas/views.py
import os

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import (
    HttpResponseRedirect, HttpResponseForbidden,
    HttpResponseNotFound, HttpResponseServerError,
    HttpResponseBadRequest, FileResponse, Http404
)
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, DeleteView

from schemas.forms import SchemaForm, ColumnCreateFormSet, ColumnUpdateFormSet
from schemas.models import Schema, Column, DataSet
from schemas.tasks import task
from schemas.utils import (
    get_dataset_path, get_fieldnames,
    get_fieldtypes, is_owner
)


class ListSchemaView(LoginRequiredMixin, ListView):
    login_url = reverse_lazy('users:login')
    model = Schema
    template_name = 'schemas/list.html'

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class CreateSchemaView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def get(self, request):
        schema_form = SchemaForm()
        column_formset = ColumnCreateFormSet(queryset=Column.objects.none())
        context = {
            'schema_form': schema_form,
            'column_formset': column_formset,
        }
        return render(request, 'schemas/create.html', context)

    def post(self, request):
        schema_form = SchemaForm(request.POST)
        column_formset = ColumnCreateFormSet(request.POST)
        if schema_form.is_valid() and column_formset.is_valid():
            schema = schema_form.save(commit=False)
            schema.user = request.user
            schema.save()
            for column_form in column_formset:
                column = column_form.save(commit=False)
                column.schema = schema
                column.save()
            return HttpResponseRedirect(reverse('schemas:list'))
        context = {
            'schema_form': schema_form,
            'column_formset': column_formset,
        }
        return render(request, 'schemas/create.html', context)


class UpdateSchemaView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def get(self, request, pk):
        schema = get_object_or_404(Schema, pk=pk)
        is_owner(request.user, schema)
        schema_form = SchemaForm(instance=schema)
        column_formset = ColumnUpdateFormSet(
            queryset=Column.objects.filter(schema_id=pk)
        )
        context = {
            'schema_form': schema_form,
            'column_formset': column_formset
        }
        return render(request, 'schemas/update.html', context)

    def post(self, request, pk):
        schema = get_object_or_404(Schema, pk=pk)
        is_owner(request.user, schema)
        schema_form = SchemaForm(request.POST, instance=schema)
        column_formset = ColumnUpdateFormSet(
            request.POST,
            queryset=Column.objects.filter(schema_id=pk)
        )
        if schema_form.is_valid() and column_formset.is_valid():
            schema_form.save()
            for column_form in column_formset:
                column_form.save()
            return HttpResponseRedirect(reverse('schemas:list'))
        context = {
            'schema_form': schema_form,
            'column_formset': column_formset
        }
        return render(request, 'schemas/update.html', context)


class DeleteSchemaView(LoginRequiredMixin, DeleteView):
    login_url = reverse_lazy('users:login')
    model = Schema
    success_url = reverse_lazy('schemas:list')
    template_name = 'schemas/delete.html'

    def get(self, request, pk):
        schema = get_object_or_404(Schema, pk=pk)
        is_owner(request.user, schema)
        return super().get(request, pk)


class RetrieveSchemaView(LoginRequiredMixin, View):
    login_url = reverse_lazy('users:login')

    def get(self, request, pk):
        schema = get_object_or_404(Schema, pk=pk)
        is_owner(request.user, schema)
        context = {
            'schema': schema,
            'column_list': schema.columns.all(),
            'dataset_list': schema.datasets.order_by('created')
        }
        return render(request, 'schemas/retrieve.html', context)


def generate_file_view(request, pk):
    schema = get_object_or_404(Schema, pk=pk)
    is_owner(request.user, schema)
    dataset_sequence_number = DataSet.get_next_sequence_number(schema.id)
    records_number = int(request.POST['records_number'])
    dataset_path = get_dataset_path(
        schema.user.username,
        schema.name,
        dataset_sequence_number
    )
    column_separator = schema.column_separator
    string_character = schema.string_character
    fieldnames = get_fieldnames(schema)
    fieldtypes = get_fieldtypes(schema)

    dataset = DataSet.objects.create(
        schema=schema,
        status="Processing",
        path=dataset_path
    )
    task(records_number, dataset_path, column_separator,
         string_character, fieldnames, fieldtypes, dataset.id)
    return HttpResponseRedirect(reverse('schemas:retrieve', args={schema.id}))


def download_file_view(request, pk):
    dataset = get_object_or_404(DataSet, pk=pk)
    is_owner(request.user, dataset.schema)
    dataset_path = dataset.path
    if os.path.exists(dataset_path):
        with open(dataset_path, 'r') as dataset_file:
            response = FileResponse(dataset_file.read(), as_attachment=True)
            response['Content-Disposition'] = (
                'attachment; filename=' + os.path.basename(dataset_path)
            )
            return response
    raise Http404


def handler400(request, exception=None):
    return HttpResponseBadRequest(render(request, 'schemas/errors/400.html'))


def handler403(request, exception):
    return HttpResponseForbidden(render(request, 'schemas/errors/403.html'))


def handler404(request, exception):
    return HttpResponseNotFound(render(request, 'schemas/errors/404.html'))


def handler500(request, exception=None):
    return HttpResponseServerError(render(request, 'schemas/errors/500.html'))

backend/schemas/templates/schemas/base.html
<!DOCTYPE HTML>
<html>
<head>
    <!-- Title block -->
    <title>
        {% block title %}{% endblock %}
    </title>

    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- Bootstrap -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    <!-- Navbar -->
    <nav class="navbar sticky-top navbar-expand-lg bg-light">
        <span class="navbar-brand mb-0 h1" style="margin: 0 0 0 30px">FakeCSV</span>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-item nav-link active text-dark" href="{% url 'schemas:list' %}" style="margin: 0 0 0 50px">Schemas</a>
          </div>
          <div class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
              <span class="navbar-text text-dark" style="margin: 0 30px 0 0">Hello, {{ user.username }}</span>
              <a class="nav-item nav-link active text-dark" href="{% url 'users:logout' %}" style="margin: 0 30px 0 0">Logout</a>
            {% endif %}
          </div>
        </div>
    </nav>

    <!-- Content block -->
    {% block content %}{% endblock %}

    <!-- Bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

backend/schemas/templates/schemas/create.html
{% extends 'schemas/base.html' %}

{% block title %}
New schema
{% endblock %}

{% block content %}
    <div style="margin: 30px 60px 100px">
        <form id="form-container" method="POST" action="{% url 'schemas:create' %}">
            {% csrf_token %}

            <div class="row">
                <div class="col">
                    <h3>New schema</h3>
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>

            {% for field in schema_form %}
                <div>{{ field.errors }}</div>
                <div>{{ field.label }}</div>
                <div style="margin: 0 0 20px 0">{{ field }}</div>
            {% endfor %}

            <h3>Schema column</h3>
            {{ column_formset.management_form }}
            {% for column_form in column_formset %}
                <div class="column-form form-row">
                {% for field in column_form %}
                    <div>{{ field.errors }}</div>
                    {% if field.label != 'Id' %}
                        <div style="margin: 0 10px 15px 0">{{ field.label }}</div>
                    {% endif %}
                    <div style="margin: 0 20px 15px 0">{{ field }}</div>
                {% endfor %}
                </div>
            {% endfor %}
            <button class="btn btn-primary" id="add-form" type="button">Add column</button>
        </form>
    </div>

    <script>
        let columnForm = document.querySelectorAll(".column-form")
        let container = document.querySelector("#form-container")
        let addButton = document.querySelector("#add-form")
        let totalForms = document.querySelector("#id_form-TOTAL_FORMS")

        let formNum = columnForm.length-1
        addButton.addEventListener('click', addForm)

        function addForm(e){
            e.preventDefault()

            let newForm = columnForm[0].cloneNode(true)
            let formRegex = RegExp(`form-(\\d){1}-`,'g')

            formNum++
            newForm.innerHTML = newForm.innerHTML.replace(formRegex, `form-${formNum}-`)
            container.insertBefore(newForm, addButton)
            
            totalForms.setAttribute('value', `${formNum+1}`)
        }
    </script>
{% endblock %}

backend/schemas/templates/schemas/delete.html
{% extends 'schemas/base.html' %}

{% block title %}
Delete schema
{% endblock %}

{% block content %}
    <div style="margin: 30px 60px 100px">
        <h3>Delete schema</h3>
        <form method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }}"?</p>
            {{ form }}
            <input type="submit" value="Confirm">
        </form>
    </div>
{% endblock %}

backend/schemas/templates/schemas/list.html
{% extends 'schemas/base.html' %}

{% block title %}
Data schemas
{% endblock %}

{% block content %}
    <div style="margin: 30px 60px 100px; width: 80%"">
        <div class="row">
            <div class="col">
                <h3>Data schemas</h3>
            </div>
            <div class="col">
                <a href="{% url 'schemas:create' %}" class="btn btn-success float-right">New schema</a>
            </div>
        </div>

        <table class="mt-3 table table-bordered table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Title</th>
                    <th>Modified</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for schema in schema_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <a href="{% url 'schemas:retrieve' schema.id %}">{{ schema.name }}</a>
                    </td>
                    <td>{{ schema.modified|date:"Y-m-d" }}</td>
                    <td>
                        <a href="{% url 'schemas:update' schema.id %}">Edit schema</a>
                        <a href="{% url 'schemas:delete' schema.id %}" class="text-danger">Delete</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

backend/schemas/templates/schemas/retrieve.html
{% extends 'schemas/base.html' %}

{% block title %}
Data sets
{% endblock %}

{% block content %}
    <div style="margin: 30px 60px 100px">
        <div class="row">
            <div class="col">
                <h3>{{ schema.name }}</h3>
            </div>
            <div class="col">
                <a href="{% url 'schemas:update' schema.id %}">Edit schema</a>
            </div>
        </div>

        <div style="width: 50%;">
            <table class="mt-3 table table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Column name</th>
                        <th>Column type</th>
                    </tr>
                </thead>
                <tbody>
                    {% for column in column_list %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ column.name }}</td>
                        <td>{{ column.get_type_name }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="col">
                <h3>Data sets</h3>
            </div>
            <div class="col">
                <form method="POST" id="generate-form" action="{% url 'schemas:generate' schema.id %}">
                    {% csrf_token %}
                    <span style="margin: 0 10px 0 0">Rows:</span>
                    <input name="records_number" type="text" style="margin: 0 10px 0 0">
                    <button class="btn btn-success" type="submit" id="generate-button" style="margin: 0 10px 0 0">Generate data</button>
                </form> 
            </div>
        </div>

        <table class="mt-3 table table-bordered table-hover">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Created</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                {% for dataset in dataset_list %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>{{ dataset.created|date:"Y-m-d" }}</td>
                    <td>
                        {% if dataset.status == 'Ready' %}
                            <span class="btn btn-success">{{ dataset.status }}</span>
                        {% else %}
                            <span class="btn btn-secondary">{{ dataset.status }}</span>
                        {% endif %}
                    </td>
                    <td>
                        {% if dataset.status == "Ready" %}
                            <a href="{% url 'schemas:download' dataset.id %}">Download file</a>
                        {% endif %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <!-- AJAX scripts -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $("#generate-form").submit(function(event) {
                event.preventDefault();
                var form = $(this);
                var url = form.attr("action");
                var formData = form.serialize();
    
                $.ajax({
                    url: url,
                    type: 'POST',
                    data: formData,
                    success: function(response) {
                        $('input[name="records_number"]').val('');
                    },
                    error: function(xhr, status, error) {
                    }
                });
            });
        });
    </script>     

    <!-- Page reloading scripts -->
    <script>  
        $(document).ready(function() {
            setInterval(function() {
            }, 30000);
        });
    </script>

{% endblock %}

backend/schemas/templates/schemas/update.html
{% extends 'schemas/base.html' %}

{% block title %}
Update schema
{% endblock %}

{% block content %}
    <div style="margin: 30px 60px 100px">
        <form id="form-container" method="POST">
            {% csrf_token %}

            <div class="row">
                <div class="col">
                    <h3>Update schema</h3>
                </div>
                <div class="col">
                    <button class="btn btn-primary" type="submit">Submit</button>
                </div>
            </div>

            {% for field in schema_form %}
                <div>{{ field.errors }}</div>
                <div>{{ field.label }}</div>
                <div style="margin: 0 0 20px 0">{{ field }}</div>
            {% endfor %}

            <h3>Schema column</h3>
            {{ column_formset.management_form }}
            {% for column_form in column_formset %}
                <div class="column-form form-row">
                {% for field in column_form %}
                    <div>{{ field.errors }}</div>
                    {% if field.label != 'Id' %}
                        <div style="margin: 0 10px 15px 0">{{ field.label }}</div>
                    {% endif %}
                    <div style="margin: 0 20px 15px 0">{{ field }}</div>
                {% endfor %}
                </div>
            {% endfor %}
        </form>
    </div>
{% endblock %}